# Generated by Django 4.2.6 on 2023-10-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='published',
            field=models.DateTimeField(null=True),
        ),
    ]
