# Generated by Django 4.2.6 on 2023-10-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0002_alter_energydata_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='country',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='pestle',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='region',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='sector',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='source',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='start_year',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='topic',
            field=models.CharField(max_length=1000),
        ),
    ]
