# Generated by Django 4.2.6 on 2023-10-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0003_alter_energydata_country_alter_energydata_pestle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='end_year',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
