# Generated by Django 4.2.6 on 2023-10-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0006_alter_energydata_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='intensity',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
