# Generated by Django 4.2.6 on 2023-10-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0007_alter_energydata_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='likelihood',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
