# Generated by Django 4.2.6 on 2023-10-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0008_alter_energydata_likelihood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='relevance',
            field=models.CharField(max_length=1000),
        ),
    ]
