# Generated by Django 4.2.6 on 2023-10-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0009_alter_energydata_relevance'),
    ]

    operations = [
        migrations.AddField(
            model_name='energydata',
            name='year',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
